(function (root) {
  'use strict';
  var YL = root.YL = root.YL || {};
  YL.W = 750;
  YL.H = 1334;
  YL.COLORS = {
    ink: '#07111d', ink2: '#101c29', panel: '#16202a',
    paper: '#f4ddb0', gold: '#dba84c', gold2: '#8b5a23',
    red: '#d94a35', red2: '#8f261f', fire: '#ff8a36',
    jade: '#47d8b1', teal: '#15958d', blue: '#58bde9',
    white: '#fff7df', muted: '#98a6a2', danger: '#ef5d56'
  };
  YL.ASSETS = {
    battlefield: 'assets/art/battlefield.webp',
    title: 'assets/art/title-keyart.webp',
    characters: 'assets/art/character-atlas.webp',
    icons: 'assets/art/icon-atlas.webp',
    heroHongyi: 'assets/art/sprites/hero-hongyi-v3.png',
    heroQingyi: 'assets/art/sprites/hero-qingyi-v3.png',
    heroHuangjin: 'assets/art/sprites/hero-huangjin-v3.png',
    heroHongyiWalk: 'assets/art/vfx/hero-action-v1/hongyi-walk-packed.png',
    heroHuangjinSafeBody: 'assets/art/rig-preview/huangjin-standard-v1/body-no-shield.png',
    heroHuangjinSafeShield: 'assets/art/skeleton/huangjin-v2/shield.png',
    heroHuangjinBody: 'assets/art/skeleton/huangjin-v1/body.png',
    heroHuangjinHead: 'assets/art/skeleton/huangjin-v1/head.png',
    heroHuangjinShield: 'assets/art/skeleton/huangjin-v1/shield.png',
    heroHuangjinRigHead: 'assets/art/skeleton/huangjin-v2/head.png',
    heroHuangjinRigBody: 'assets/art/skeleton/huangjin-v2/body.png',
    heroHuangjinRigBase: 'assets/art/skeleton/huangjin-v2/base.png',
    heroHuangjinRigShield: 'assets/art/skeleton/huangjin-v2/shield.png',
    heroHuangjinRigLeftUpperArm: 'assets/art/skeleton/huangjin-v2/left_upper_arm.png',
    heroHuangjinRigLeftForearm: 'assets/art/skeleton/huangjin-v2/left_forearm.png',
    heroHuangjinRigRightArm: 'assets/art/skeleton/huangjin-v2/right_arm.png',
    heroHuangjinRigLeftLeg: 'assets/art/skeleton/huangjin-v2/left_leg.png',
    heroHuangjinRigRightLeg: 'assets/art/skeleton/huangjin-v2/right_leg.png',
    heroHuangjinRigCape: 'assets/art/skeleton/huangjin-v2/cape.png',
    heroXuanya: 'assets/art/sprites/hero-xuanya-v3.png',
    heroSuwen: 'assets/art/sprites/hero-suwen-v3.png',
    heroAttackHongyi: 'assets/art/vfx/attack-frames-v3/hongyi-mature-packed.png',
    heroAttackHuangjinBash: 'assets/art/vfx/attack-frames-v3/huangjin-shield-bash-packed.png',
    huangjinWallShockwaveBasic: 'assets/art/vfx/huangjin-wall-v1/huangjin-shockwave-basic.png',
    huangjinWallShockwaveFan: 'assets/art/vfx/huangjin-wall-v1/huangjin-shockwave-fan.png',
    huangjinWallSuppressSeal: 'assets/art/vfx/huangjin-wall-v1/huangjin-suppress-seal.png',
    heroAttackXuanya: 'assets/art/vfx/attack-frames-v3/xuanya-mature-packed.png',
    heroAttackSuwen: 'assets/art/vfx/attack-frames-v3/suwen-mature-normalized.png',
    heroAttackQingyi: 'assets/art/vfx/attack-frames-v3/qingyi-mature-normalized.png',
    enemyWispAttackVfx: 'assets/art/vfx/attack-frames-v3/enemy-wisp-attack-packed.png',
    rangedOrbsVfx: 'assets/art/vfx/ranged-orbs-atlas.webp',
    meleeSlashesVfx: 'assets/art/vfx/melee-slashes-atlas.webp',
    statusShieldAura: 'assets/art/vfx/status/shield-aura-v1.png',
    statusGuardDragon: 'assets/art/vfx/status/guard-dragon-v1.png',
    taoistMain: 'assets/art/ui/taoist-main-v3.png',
    battleFormationOverlay: 'assets/art/ui/battle-lower-v1/battle-formation-blue-v5.png',
    battleLowerHealthFrame: 'assets/art/ui/battle-lower-v1/health-bar-frame.png',
    battleLowerHealthFill: 'assets/art/ui/battle-lower-v1/health-bar-fill.png',
    baguaFormation: 'assets/art/ui/bagua-formation-v3.png',
    spiritLamp: 'assets/art/ui/spirit-lamp-v3.png',
    spiritLampStates: 'assets/art/ui/spirit-lamp-states-v4.png',
    spellIcons: 'assets/art/ui/spell-icons-v2.png',
    formationIcons: 'assets/art/ui/formation-icon-atlas-v1.png',
    hudControlIcons: 'assets/art/ui/hud-control-icons-v2.png',
    hudSpeedBase: 'assets/art/ui/hud-speed-base-v1.png',
    hudSpeedGlyphX: 'assets/art/ui/hud-speed-x-v1.png',
    hudSpeedGlyph1: 'assets/art/ui/hud-speed-1-v1.png',
    hudSpeedGlyph2: 'assets/art/ui/hud-speed-2-v1.png',
    hudSpeedGlyph3: 'assets/art/ui/hud-speed-3-v1.png',
    hudProgressFrame: 'assets/art/ui/hud-progress-frame-v2.png',
    hudProgressOrnament: 'assets/art/ui/hud-progress-ornament-v3.png',
    upgradeCardFrames: 'assets/art/ui/upgrade-card-frames-v1.png',
    upgradeCardOrnaments: 'assets/art/ui/upgrade-card-ornaments-v1.png',
    upgradeStarFilled: 'assets/art/ui/upgrade-star-filled-v1.png',
    upgradeStarEmpty: 'assets/art/ui/upgrade-star-empty-v1.png',
    talismanControl: 'assets/art/ui/talisman-control-v1.png',
    talismanCountBadge: 'assets/art/ui/talisman-count-badge-v1.png',
    talismanModalPanel: 'assets/art/ui/talisman-modal-panel-v1.png',
    talismanRowCommon: 'assets/art/ui/talisman-row-common-v1.png',
    talismanRowRare: 'assets/art/ui/talisman-row-rare-v1.png',
    talismanRowLegendary: 'assets/art/ui/talisman-row-legendary-v1.png',
    enemyWisp: 'assets/art/sprites/enemy-wisp.webp',
    enemyJiangshi: 'assets/art/sprites/enemy-jiangshi.webp',
    enemyBoss: 'assets/art/sprites/enemy-boss-transparent.webp'
  };
  YL.AUDIO = {
    main: 'assets/audio/main.mp3',
    battle: 'assets/audio/battle.mp3'
  };
  YL.SFX = {
    uiTap: 'assets/audio/sfx/sfx_ui_tap_confirm.mp3',
    uiCardOpen: 'assets/audio/sfx/sfx_ui_card_open.mp3',
    upgradeCommon: 'assets/audio/sfx/sfx_ui_upgrade_pick_common.mp3',
    upgradeRare: 'assets/audio/sfx/sfx_ui_upgrade_pick_rare.mp3',
    upgradeLegendary: 'assets/audio/sfx/sfx_ui_upgrade_pick_legendary.mp3',
    waveStart: 'assets/audio/sfx/sfx_wave_start.mp3',
    waveClear: 'assets/audio/sfx/sfx_wave_clear.mp3',
    bossAppear: 'assets/audio/sfx/sfx_boss_appear.mp3',
    enemyHit: 'assets/audio/sfx/sfx_enemy_hit_soft.mp3',
    enemyDie: 'assets/audio/sfx/sfx_enemy_die_paper.mp3',
    wallHitLight: 'assets/audio/sfx/sfx_wall_hit_light.mp3',
    wallHitHeavy: 'assets/audio/sfx/sfx_wall_hit_heavy.mp3',
    hongyiFireHit: 'assets/audio/sfx/sfx_hongyi_fire_hit.mp3',
    huangjinDrumWave: 'assets/audio/sfx/sfx_huangjin_drum_wave.mp3',
    xuanyaBladeHit: 'assets/audio/sfx/sfx_xuanya_blade_hit.mp3',
    spellWind: 'assets/audio/sfx/sfx_spell_wind.mp3',
    spellRain: 'assets/audio/sfx/sfx_spell_rain.mp3',
    runeDrop: 'assets/audio/sfx/sfx_rune_drop.mp3',
    runePickup: 'assets/audio/sfx/sfx_rune_pickup.mp3',
    runeEquip: 'assets/audio/sfx/sfx_rune_equip.mp3',
    energyFull: 'assets/audio/sfx/sfx_energy_full.mp3',
    ultimateHongyi: 'assets/audio/sfx/sfx_ultimate_hongyi.mp3',
    ultimateHuangjin: 'assets/audio/sfx/sfx_ultimate_huangjin.mp3',
    ultimateXuanya: 'assets/audio/sfx/sfx_ultimate_xuanya.mp3',
    victory: 'assets/audio/sfx/sfx_victory.mp3',
    defeat: 'assets/audio/sfx/sfx_defeat.mp3'
  };
}(typeof globalThis !== 'undefined' ? globalThis : this));
